#!/usr/bin/env bash

if [[ $1 == '-h' ]] || [[ $1 == '-help' ]] || [[ $1 == '--help' ]]; then
  echo "$0 "'$filepath:$line:$range' 1>&2
  exit 1
fi

cmdcheck() {
  type -a "$1" >/dev/null 2>&1
}

main() {
  local file_path range line_no
  file_path="${*%%:*}"
  range=$(echo "$@" | awk -F':' '{ if ( $3 != "" ) print $3; else print $4; }')
  if [[ -z $range ]]; then
    # NOTE: default range
    range=5
  fi
  line_no=$(echo "$@" | awk -F':' '{print $2}')
  if [[ -z $line_no ]]; then
    line_no=0
    # NOTE: infinite range
    range=9999999
  fi

  cat_cmd() { cat -n "$@"; }
  local pre_line=0
  if cmdcheck bat; then
    # NOTE: bat has --line-range <start>:<end> option
    cat_cmd() { bat --color=always "$@"; }
    pre_line=3
  elif cmdcheck ccat; then
    cat_cmd() { ccat -C=always "$@"; }
    pre_line=0
  fi

  local awk_reg='^(\033\[0m)?\033\[38;5;238m *'"$line_no"'[^0-9]'
  cat_cmd "$file_path" | awk -v base=$line_no -v range=$range -v pre_line=$pre_line '(pre_line+base-range)<=NR && NR<=(pre_line+base+range)' |
    # NOTE: replace color of line number of bat
    awk '! /'"$awk_reg"'/{print $0;} /'"$awk_reg"'/{gsub("\033\\[[0-9]m","\033[4m",$0); gsub("\033\\[38;5;238m","\033[4m",$0); printf "%s%s\n", $0,"\033[0m"; }'
}

main "$@"
